const {test}=require('node:test');const assert=require('node:assert/strict');
let definition;global.Page=d=>definition=d;const storage=new Map();let listener,removed,navigation=[];
global.wx={getStorageSync:k=>storage.get(k),setStorageSync:(k,v)=>storage.set(k,v),removeStorageSync:k=>storage.delete(k),getStorageInfoSync:()=>({keys:[...storage.keys()]}),navigateTo:o=>navigation.push(o.url),nextTick:f=>f(),onNetworkStatusChange:f=>listener=f,offNetworkStatusChange:f=>removed=f,getNetworkType:o=>o.success({networkType:'none'})};
const {content}=require('../models/content');
require('../models/auth').auth.session={user:{id:'test-member'}};
function make(name){const f=require.resolve('../pages/'+name+'/'+name+'.js');delete require.cache[f];require(f);return{...definition,data:structuredClone(definition.data),setData(d){Object.assign(this.data,d)}}}
const tick=()=>new Promise(r=>setImmediate(r));
test('explicit load-more uses cursor, deduplicates books, hides after final page',async()=>{let calls=[];content.list=async(a,c)=>{calls.push([a,c]);return{items:[{bookId:c?'two':'one',title:c?'Letters from the Coast':'Harry Potter and the Philosopher’s Stone',language:'en',edition:'原创版',chapterCount:8,contentChapterCount:8,chapterAudioAvailableCount:c?8:0}],nextCursor:c?null:'next'}};const p=make('library');p.onLoad();await tick();assert.equal(p.data.books[0].coverInitials,'HP');assert.equal(p.data.books[0].audioComplete,false);await p.loadMore();assert.deepEqual(calls[1],['member','next']);assert.equal(p.data.books.length,2);assert.equal(p.data.books[1].coverInitials,'LC');assert.equal(p.data.books[1].audioComplete,true);assert.equal(p.data.nextCursor,null);await p.loadMore();assert.equal(calls.length,2);p.onUnload()});
test('reader observes real network changes and detaches listener on unload',async()=>{content.book=async()=>{throw Error('test unavailable')};const p=make('reader');p.onLoad({bookId:'b'});await tick();assert.equal(p.data.offline,true);listener({isConnected:true});assert.equal(p.data.offline,false);p.onUnload();assert.equal(removed,listener);listener({isConnected:false});assert.equal(p.data.offline,false)});
test('custom navigation respects capsule inset and root route fallback',()=>{global.Component=d=>definition=d;global.getCurrentPages=()=>[{}];wx.getWindowInfo=()=>({statusBarHeight:47,windowWidth:390});wx.getMenuButtonBoundingClientRect=()=>({top:51,height:32,left:291});wx.reLaunch=o=>navigation.push(o.url);require('../components/nav/nav');const c={data:{...definition.data},setData(d){Object.assign(this.data,d)}};definition.lifetimes.attached.call(c);assert.deepEqual(c.data,{statusBarHeight:47,barHeight:40,rightInset:111});definition.methods.goBack();assert.equal(navigation.at(-1),'/pages/library/library')});
